services:
  studio-dev:
    build:
      context: ../..
      dockerfile: docker/development/Dockerfile
    ports:
      - "3000:3000"
    environment:
      NODE_ENV: "development"
      NEXT_TELEMETRY_DISABLED: "1"
    volumes:
      - ../../.files:/usr/src/app/.files
    command: ["npm", "run", "dev"]
