services:
  studio:
    build:
      context: ../..
      dockerfile: docker/production/Dockerfile
    ports:
      - "4000:3000"
    environment:
      NODE_ENV: "production"
      NEXT_TELEMETRY_DISABLED: "1"
    volumes:
      - ../../.files:/usr/src/app/.files
    command: ["npm", "start"]
